apiVersion: v1
data:
  cloud.conf: |
    [Global]
    use-clouds = true
    clouds-file = /etc/openstack/secret/clouds.yaml
    cloud = openstack
kind: ConfigMap
metadata:
  name: openstack-cloud-controller-manager-config
  namespace: openshift-cloud-controller-manager
