apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-controller-manager
  namespace: openshift-cloud-controller-manager
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  kind: Role
  name: openstack-cloud-controller-manager
subjects:
  - kind: ServiceAccount
    namespace: openshift-cloud-controller-manager
    name: cloud-controller-manager
