apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openstack-cloud-controller-manager
  namespace: openshift-cloud-controller-manager
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - create
      - update

  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - watch
      - list
      - patch
